/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fatin.logical_calculator;

import java.awt.Color;

/**
 *
 * @author moham
 */
public class Calculator extends javax.swing.JFrame {
    String s="0";
    int active=2;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        bA.setForeground(Color.gray);
        bB.setForeground(Color.gray);
        bC.setForeground(Color.gray);
        bD.setForeground(Color.gray);
        bE.setForeground(Color.gray);
        bF.setForeground(Color.gray);
        bA.setEnabled(false);
        bB.setEnabled(false);
        bC.setEnabled(false);
        bD.setEnabled(false);
        bE.setEnabled(false);
        bF.setEnabled(false);
        p1.setBackground(Color.decode("#352F44"));
        p3.setBackground(Color.decode("#352F44"));
        p4.setBackground(Color.decode("#352F44"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tf = new javax.swing.JTextField();
        p1 = new javax.swing.JPanel();
        type1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        tyoe2 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        type3 = new javax.swing.JLabel();
        type4 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        hex = new javax.swing.JLabel();
        dec = new javax.swing.JLabel();
        oct = new javax.swing.JLabel();
        bin = new javax.swing.JLabel();
        AC = new javax.swing.JPanel();
        bA = new javax.swing.JButton();
        bB = new javax.swing.JButton();
        bAC = new javax.swing.JButton();
        bCCC = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        bD = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bF = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bE = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();

        jButton1.setBackground(new java.awt.Color(92, 84, 112));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(250, 240, 230));
        jButton1.setText("A");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setMaximumSize(new java.awt.Dimension(28, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(28, 25));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(53, 47, 68));

        tf.setEditable(false);
        tf.setBackground(new java.awt.Color(53, 47, 68));
        tf.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tf.setForeground(new java.awt.Color(250, 240, 230));
        tf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tf.setText("0");
        tf.setBorder(null);

        p1.setBackground(new java.awt.Color(185, 180, 199));
        p1.setPreferredSize(new java.awt.Dimension(5, 15));

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        type1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        type1.setForeground(new java.awt.Color(250, 240, 230));
        type1.setText("HEX");
        type1.setPreferredSize(new java.awt.Dimension(30, 18));
        type1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                type1MouseClicked(evt);
            }
        });

        p2.setBackground(new java.awt.Color(185, 180, 199));
        p2.setPreferredSize(new java.awt.Dimension(5, 15));

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tyoe2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tyoe2.setForeground(new java.awt.Color(250, 240, 230));
        tyoe2.setText("DEC");
        tyoe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tyoe2MouseClicked(evt);
            }
        });

        p3.setBackground(new java.awt.Color(185, 180, 199));
        p3.setPreferredSize(new java.awt.Dimension(5, 15));

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        type3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        type3.setForeground(new java.awt.Color(250, 240, 230));
        type3.setText("OCT");
        type3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                type3MouseClicked(evt);
            }
        });

        type4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        type4.setForeground(new java.awt.Color(250, 240, 230));
        type4.setText("BIN");
        type4.setMaximumSize(new java.awt.Dimension(30, 18));
        type4.setPreferredSize(new java.awt.Dimension(30, 18));
        type4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                type4MouseClicked(evt);
            }
        });

        p4.setBackground(new java.awt.Color(185, 180, 199));
        p4.setPreferredSize(new java.awt.Dimension(5, 15));

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        hex.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        hex.setForeground(new java.awt.Color(250, 240, 230));
        hex.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hex.setText("0");

        dec.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dec.setForeground(new java.awt.Color(250, 240, 230));
        dec.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dec.setText("0");

        oct.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        oct.setForeground(new java.awt.Color(250, 240, 230));
        oct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        oct.setText("0");

        bin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bin.setForeground(new java.awt.Color(250, 240, 230));
        bin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bin.setText("0");

        AC.setBackground(new java.awt.Color(53, 47, 68));

        bA.setBackground(new java.awt.Color(92, 84, 112));
        bA.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bA.setForeground(new java.awt.Color(250, 240, 230));
        bA.setText("A");
        bA.setBorderPainted(false);
        bA.setFocusable(false);
        bA.setMaximumSize(new java.awt.Dimension(28, 25));
        bA.setPreferredSize(new java.awt.Dimension(28, 25));
        bA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAActionPerformed(evt);
            }
        });

        bB.setBackground(new java.awt.Color(92, 84, 112));
        bB.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bB.setForeground(new java.awt.Color(250, 240, 230));
        bB.setText("B");
        bB.setBorderPainted(false);
        bB.setFocusable(false);
        bB.setMaximumSize(new java.awt.Dimension(28, 25));
        bB.setPreferredSize(new java.awt.Dimension(28, 25));
        bB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBActionPerformed(evt);
            }
        });

        bAC.setBackground(new java.awt.Color(160, 21, 62));
        bAC.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bAC.setForeground(new java.awt.Color(250, 240, 230));
        bAC.setText("AC");
        bAC.setBorderPainted(false);
        bAC.setFocusable(false);
        bAC.setMaximumSize(new java.awt.Dimension(28, 25));
        bAC.setPreferredSize(new java.awt.Dimension(28, 25));
        bAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bACActionPerformed(evt);
            }
        });

        bCCC.setBackground(new java.awt.Color(160, 21, 62));
        bCCC.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bCCC.setForeground(new java.awt.Color(250, 240, 230));
        bCCC.setText("C");
        bCCC.setBorderPainted(false);
        bCCC.setFocusable(false);
        bCCC.setMaximumSize(new java.awt.Dimension(28, 25));
        bCCC.setPreferredSize(new java.awt.Dimension(28, 25));
        bCCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCCCActionPerformed(evt);
            }
        });

        bC.setBackground(new java.awt.Color(92, 84, 112));
        bC.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bC.setForeground(new java.awt.Color(250, 240, 230));
        bC.setText("C");
        bC.setBorderPainted(false);
        bC.setFocusable(false);
        bC.setMaximumSize(new java.awt.Dimension(28, 25));
        bC.setPreferredSize(new java.awt.Dimension(28, 25));
        bC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCActionPerformed(evt);
            }
        });

        bD.setBackground(new java.awt.Color(92, 84, 112));
        bD.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bD.setForeground(new java.awt.Color(250, 240, 230));
        bD.setText("D");
        bD.setBorderPainted(false);
        bD.setFocusable(false);
        bD.setMaximumSize(new java.awt.Dimension(28, 25));
        bD.setPreferredSize(new java.awt.Dimension(28, 25));
        bD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(92, 84, 112));
        b7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b7.setForeground(new java.awt.Color(250, 240, 230));
        b7.setText("7");
        b7.setBorderPainted(false);
        b7.setFocusable(false);
        b7.setMaximumSize(new java.awt.Dimension(28, 25));
        b7.setPreferredSize(new java.awt.Dimension(28, 25));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(92, 84, 112));
        b8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b8.setForeground(new java.awt.Color(250, 240, 230));
        b8.setText("8");
        b8.setBorderPainted(false);
        b8.setFocusable(false);
        b8.setMaximumSize(new java.awt.Dimension(28, 25));
        b8.setPreferredSize(new java.awt.Dimension(28, 25));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(92, 84, 112));
        b9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b9.setForeground(new java.awt.Color(250, 240, 230));
        b9.setText("9");
        b9.setBorderPainted(false);
        b9.setFocusable(false);
        b9.setMaximumSize(new java.awt.Dimension(28, 25));
        b9.setPreferredSize(new java.awt.Dimension(28, 25));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        bF.setBackground(new java.awt.Color(92, 84, 112));
        bF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bF.setForeground(new java.awt.Color(250, 240, 230));
        bF.setText("F");
        bF.setBorderPainted(false);
        bF.setFocusable(false);
        bF.setMaximumSize(new java.awt.Dimension(28, 25));
        bF.setPreferredSize(new java.awt.Dimension(28, 25));
        bF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(92, 84, 112));
        b5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b5.setForeground(new java.awt.Color(250, 240, 230));
        b5.setText("5");
        b5.setBorderPainted(false);
        b5.setFocusable(false);
        b5.setMaximumSize(new java.awt.Dimension(28, 25));
        b5.setPreferredSize(new java.awt.Dimension(28, 25));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(92, 84, 112));
        b6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b6.setForeground(new java.awt.Color(250, 240, 230));
        b6.setText("6");
        b6.setBorderPainted(false);
        b6.setFocusable(false);
        b6.setMaximumSize(new java.awt.Dimension(28, 25));
        b6.setPreferredSize(new java.awt.Dimension(28, 25));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        bE.setBackground(new java.awt.Color(92, 84, 112));
        bE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bE.setForeground(new java.awt.Color(250, 240, 230));
        bE.setText("E");
        bE.setBorderPainted(false);
        bE.setFocusable(false);
        bE.setMaximumSize(new java.awt.Dimension(28, 25));
        bE.setPreferredSize(new java.awt.Dimension(28, 25));
        bE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(92, 84, 112));
        b4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b4.setForeground(new java.awt.Color(250, 240, 230));
        b4.setText("4");
        b4.setBorderPainted(false);
        b4.setFocusable(false);
        b4.setMaximumSize(new java.awt.Dimension(28, 25));
        b4.setPreferredSize(new java.awt.Dimension(28, 25));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(92, 84, 112));
        b0.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b0.setForeground(new java.awt.Color(250, 240, 230));
        b0.setText("0");
        b0.setBorderPainted(false);
        b0.setFocusable(false);
        b0.setMaximumSize(new java.awt.Dimension(28, 25));
        b0.setPreferredSize(new java.awt.Dimension(28, 25));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(92, 84, 112));
        b3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b3.setForeground(new java.awt.Color(250, 240, 230));
        b3.setText("3");
        b3.setBorderPainted(false);
        b3.setFocusable(false);
        b3.setMaximumSize(new java.awt.Dimension(28, 25));
        b3.setPreferredSize(new java.awt.Dimension(28, 25));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(92, 84, 112));
        b2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b2.setForeground(new java.awt.Color(250, 240, 230));
        b2.setText("2");
        b2.setBorderPainted(false);
        b2.setFocusable(false);
        b2.setMaximumSize(new java.awt.Dimension(28, 25));
        b2.setPreferredSize(new java.awt.Dimension(28, 25));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(92, 84, 112));
        b1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(250, 240, 230));
        b1.setText("1");
        b1.setBorderPainted(false);
        b1.setFocusable(false);
        b1.setMaximumSize(new java.awt.Dimension(28, 25));
        b1.setPreferredSize(new java.awt.Dimension(28, 25));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ACLayout = new javax.swing.GroupLayout(AC);
        AC.setLayout(ACLayout);
        ACLayout.setHorizontalGroup(
            ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ACLayout.createSequentialGroup()
                        .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ACLayout.createSequentialGroup()
                                .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(b0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ACLayout.createSequentialGroup()
                        .addComponent(bA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ACLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b7, b8, b9, bC, bD});

        ACLayout.setVerticalGroup(
            ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bAC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bCCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ACLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {b0, bA, bB, bC, bD, bE, bF});

        ACLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {b1, b2, b3, b4, b5, b6, b7, b8, b9, bAC, bCCC});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tyoe2)
                        .addGap(18, 18, 18)
                        .addComponent(dec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type3)
                        .addGap(18, 18, 18)
                        .addComponent(oct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(AC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(type1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hex, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tyoe2, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                        .addComponent(dec)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(type3, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                        .addComponent(oct)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(type4, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                        .addComponent(bin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void decToAll(){
        int x=Integer.parseInt(s);
        bin.setText(Integer.toBinaryString(x));
        hex.setText(Integer.toHexString(x).toUpperCase());
        dec.setText(String.valueOf(x));
        oct.setText(Integer.toOctalString(x));
    }
    
    public void hexToAll(){
        int x=Integer.parseInt(s, 16);
        bin.setText(Integer.toBinaryString(x));
        dec.setText(String.valueOf(x));
        oct.setText(Integer.toOctalString(x)); 
        hex.setText(s.toUpperCase()); 
    }
    
    public void octToAll(){
        int x=Integer.parseInt(s, 8);
        bin.setText(Integer.toBinaryString(x));
        dec.setText(String.valueOf(x));
        hex.setText(Integer.toHexString(x).toUpperCase()); 
        oct.setText(s);
    }
    
    public void binToAll(){
        int x = Integer.parseInt(s, 2);
        bin.setText(s); 
        dec.setText(String.valueOf(x)); 
        hex.setText(Integer.toHexString(x).toUpperCase());
        oct.setText(Integer.toOctalString(x));
    }

    
    private void type1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_type1MouseClicked
        // TODO add your handling code here:
        bA.setForeground(Color.decode("#faf0e6"));
        bB.setForeground(Color.decode("#faf0e6"));
        bC.setForeground(Color.decode("#faf0e6"));
        bD.setForeground(Color.decode("#faf0e6"));
        bE.setForeground(Color.decode("#faf0e6"));
        bF.setForeground(Color.decode("#faf0e6"));
        b2.setForeground(Color.decode("#faf0e6"));
        b3.setForeground(Color.decode("#faf0e6"));
        b4.setForeground(Color.decode("#faf0e6"));
        b5.setForeground(Color.decode("#faf0e6"));
        b6.setForeground(Color.decode("#faf0e6"));
        b7.setForeground(Color.decode("#faf0e6"));
        b8.setForeground(Color.decode("#faf0e6"));
        b9.setForeground(Color.decode("#faf0e6"));
        bA.setEnabled(true);
        bB.setEnabled(true);
        bC.setEnabled(true);
        bD.setEnabled(true);
        bE.setEnabled(true);
        bF.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        p1.setBackground(Color.decode("#B9B4C7"));
        p2.setBackground(Color.decode("#352F44"));
        p3.setBackground(Color.decode("#352F44"));
        p4.setBackground(Color.decode("#352F44"));
        s=hex.getText();
        tf.setText(s);
        active=1;
        hexToAll();
    }//GEN-LAST:event_type1MouseClicked

    private void tyoe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tyoe2MouseClicked
        // TODO add your handling code here:
        bA.setForeground(Color.gray);
        bB.setForeground(Color.gray);
        bC.setForeground(Color.gray);
        bD.setForeground(Color.gray);
        bE.setForeground(Color.gray);
        bF.setForeground(Color.gray);
        bA.setEnabled(false);
        bB.setEnabled(false);
        bC.setEnabled(false);
        bD.setEnabled(false);
        bE.setEnabled(false);
        bF.setEnabled(false);
        b2.setForeground(Color.decode("#faf0e6"));
        b3.setForeground(Color.decode("#faf0e6"));
        b4.setForeground(Color.decode("#faf0e6"));
        b5.setForeground(Color.decode("#faf0e6"));
        b6.setForeground(Color.decode("#faf0e6"));
        b7.setForeground(Color.decode("#faf0e6"));
        b8.setForeground(Color.decode("#faf0e6"));
        b9.setForeground(Color.decode("#faf0e6"));
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        p2.setBackground(Color.decode("#B9B4C7"));
        p1.setBackground(Color.decode("#352F44"));
        p3.setBackground(Color.decode("#352F44"));
        p4.setBackground(Color.decode("#352F44"));
        s=dec.getText();
        tf.setText(s);
        active=2;
        decToAll();
    }//GEN-LAST:event_tyoe2MouseClicked

    private void type3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_type3MouseClicked
        // TODO add your handling code here:
        bA.setForeground(Color.gray);
        bB.setForeground(Color.gray);
        bC.setForeground(Color.gray);
        bD.setForeground(Color.gray);
        bE.setForeground(Color.gray);
        bF.setForeground(Color.gray);
        b8.setForeground(Color.gray);
        b9.setForeground(Color.gray);
        bA.setEnabled(false);
        bB.setEnabled(false);
        bC.setEnabled(false);
        bD.setEnabled(false);
        bE.setEnabled(false);
        bF.setEnabled(false);
        b8.setEnabled(false);
        b9.setEnabled(false);
        b2.setForeground(Color.decode("#faf0e6"));
        b3.setForeground(Color.decode("#faf0e6"));
        b4.setForeground(Color.decode("#faf0e6"));
        b5.setForeground(Color.decode("#faf0e6"));
        b6.setForeground(Color.decode("#faf0e6"));
        b7.setForeground(Color.decode("#faf0e6"));
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        p3.setBackground(Color.decode("#B9B4C7"));
        p2.setBackground(Color.decode("#352F44"));
        p1.setBackground(Color.decode("#352F44"));
        p4.setBackground(Color.decode("#352F44"));
        s=oct.getText();
        tf.setText(s);
        active=3;
        octToAll();
    }//GEN-LAST:event_type3MouseClicked

    private void type4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_type4MouseClicked
        // TODO add your handling code here:
        bA.setForeground(Color.gray);
        bB.setForeground(Color.gray);
        bC.setForeground(Color.gray);
        bD.setForeground(Color.gray);
        bE.setForeground(Color.gray);
        bF.setForeground(Color.gray);
        b2.setForeground(Color.gray);
        b3.setForeground(Color.gray);
        b4.setForeground(Color.gray);
        b5.setForeground(Color.gray);
        b6.setForeground(Color.gray);
        b7.setForeground(Color.gray);
        b8.setForeground(Color.gray);
        b9.setForeground(Color.gray);
        bA.setEnabled(false);
        bB.setEnabled(false);
        bC.setEnabled(false);
        bD.setEnabled(false);
        bE.setEnabled(false);
        bF.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
        b5.setEnabled(false);
        b6.setEnabled(false);
        b7.setEnabled(false);
        b8.setEnabled(false);
        b9.setEnabled(false);
        p4.setBackground(Color.decode("#B9B4C7"));
        p2.setBackground(Color.decode("#352F44"));
        p3.setBackground(Color.decode("#352F44"));
        p1.setBackground(Color.decode("#352F44"));
        s=bin.getText();
        tf.setText(s);
        active=4;
        binToAll();
    }//GEN-LAST:event_type4MouseClicked

    private void bACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bACActionPerformed
        // TODO add your handling code here:
        s="0";
        tf.setText(s);
        hex.setText(s);
        dec.setText(s);
        oct.setText(s);
        bin.setText(s);
    }//GEN-LAST:event_bACActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        s+="0";
        if(s.equals("00")) s="0";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        s+="1";
        if(s.equals("01")) s="1";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        s+="2";
        if(s.equals("02")) s="2";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        s+="3";
        if(s.equals("03")) s="3";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        s+="4";
        if(s.equals("04")) s="4";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        s+="5";
        if(s.equals("05")) s="5";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        s+="6";
        if(s.equals("06")) s="6";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        s+="7";
        if(s.equals("07")) s="7";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        s+="8";
        if(s.equals("08")) s="8";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        s+="9";
        if(s.equals("09")) s="9";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void bAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAActionPerformed
        // TODO add your handling code here:
        s+="A";
        if(s.equals("0A")) s="A";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_bAActionPerformed

    private void bBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBActionPerformed
        // TODO add your handling code here:
        s+="B";
        if(s.equals("0B")) s="B";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_bBActionPerformed

    private void bCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCActionPerformed
        // TODO add your handling code here:
        s+="C";
        if(s.equals("0C")) s="C";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_bCActionPerformed

    private void bDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDActionPerformed
        // TODO add your handling code here:
        s+="D";
        if(s.equals("0D")) s="D";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_bDActionPerformed

    private void bEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEActionPerformed
        // TODO add your handling code here:
        s+="E";
        if(s.equals("0E")) s="E";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_bEActionPerformed

    private void bFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFActionPerformed
        // TODO add your handling code here:
        s+="F";
        if(s.equals("0F")) s="F";
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_bFActionPerformed

    private void bCCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCCCActionPerformed
        // TODO add your handling code here:
        if(s.length()==1){
            s="0";
            tf.setText(s);
            hex.setText(s);
            dec.setText(s);
            oct.setText(s);
            bin.setText(s);
            return;
        }
        
        String tmp=s;
        s="";
        for(int i=0; i<tmp.length()-1; i++){
            s+=tmp.charAt(i);
        }
        tf.setText(s);
        switch (active) {
            case 1 -> hexToAll();
            case 2 -> decToAll();
            case 3 -> octToAll();
            case 4 -> binToAll();
        }
    }//GEN-LAST:event_bCCCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AC;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bA;
    private javax.swing.JButton bAC;
    private javax.swing.JButton bB;
    private javax.swing.JButton bC;
    private javax.swing.JButton bCCC;
    private javax.swing.JButton bD;
    private javax.swing.JButton bE;
    private javax.swing.JButton bF;
    private javax.swing.JLabel bin;
    private javax.swing.JLabel dec;
    private javax.swing.JLabel hex;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel oct;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JTextField tf;
    private javax.swing.JLabel tyoe2;
    private javax.swing.JLabel type1;
    private javax.swing.JLabel type3;
    private javax.swing.JLabel type4;
    // End of variables declaration//GEN-END:variables
}
